version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "monthly"
    time: "04:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 7
  target-branch: dependencies # Work around the limitation that dependabot may not merge into protected branches
  assignees:
    - "AlCalzone"
  versioning-strategy: increase
